export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const IS_LOGIN_PENDING = 'IS_LOGIN_PENDING';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const GET_ERROR_FROM_API = 'GET_ERROR_FROM_API';
export const CALCULATE_LOADING = 'CALCULATE_LOADING';
export const SET_DISCOUNT_CODE = 'SET_DISCOUNT_CODE';
export const CHANGE_OPERATOR_TYPE = 'CHANGE_OPERATOR_TYPE';
export const ACTIVE_NIGHT_MODE = 'ACTIVE_NIGHT_MODE';


/**************** Set Campaign Information ***************/
export const SET_CAMPAIGN_NAME = 'SET_CAMPAIGN_NAME';
export const SET_CAMPAIGN_SERVICE_TYPE = 'SET_CAMPAIGN_SERVICE_TYPE';
export const SET_CAMPAIGN_CHARGE_TYPE = 'SET_CAMPAIGN_CHARGE_TYPE';
export const SET_CAMPAIGN_CHARGE_AMOUNT = 'SET_CAMPAIGN_CHARGE_AMOUNT';

export const SET_CAMPAIGN_INTERNET_TYPE = 'SET_CAMPAIGN_INTERNET_TYPE';
export const SET_CAMPAIGN_CHANCE_TYPE = 'SET_CAMPAIGN_CHANCE_TYPE';
export const SET_CAMPAIGN_CHANCE_AMOUNT = 'SET_CAMPAIGN_CHANCE_AMOUNT';
export const SET_CAMPAIGN_SCORE_AMOUNT = 'SET_CAMPAIGN_SCORE_AMOUNT';

export const SET_CAMPAIGN_FROM_TIME = 'SET_CAMPAIGN_FROM_TIME';
export const SET_CAMPAIGN_TO_TIME = 'SET_CAMPAIGN_TO_TIME';
export const SET_CAMPAIGN_FROM_DATE = 'SET_CAMPAIGN_FROM_DATE';
export const SET_CAMPAIGN_TO_DATE = 'SET_CAMPAIGN_TO_DATE';
export const SET_CAMPAIGN_SMSTEXT = 'SET_CAMPAIGN_SMSTEXT';
export const SET_CAMPAIGN_RECEIVER_TYPE= 'SET_CAMPAIGN_RECEIVER_TYPE';

export const SET_CAMPAIGN_ACTION_SERVICE_TYPE = 'SET_CAMPAIGN_ACTION_SERVICE_TYPE';
export const REMOVE_CAMPAIGN_ACTION_SERVICE_TYPE = 'REMOVE_CAMPAIGN_ACTION_SERVICE_TYPE';
export const SET_CAMPAIGN_ACTION_CHARGE_TYPE = 'SET_CAMPAIGN_ACTION_CHARGE_TYPE';
export const REMOVE_CAMPAIGN_ACTION_CHARGE_TYPE = 'REMOVE_CAMPAIGN_ACTION_CHARGE_TYPE';
export const RESET_CAMPAIGN_ACTION_CHARGE_TYPE = 'RESET_CAMPAIGN_ACTION_CHARGE_TYPE';
export const SET_CAMPAIGN_ACTION_CHARGE_AMOUNT = 'SET_CAMPAIGN_ACTION_CHARGE_AMOUNT';
export const REMOVE_CAMPAIGN_ACTION_CHARGE_AMOUNT = 'REMOVE_CAMPAIGN_ACTION_CHARGE_AMOUNT';



export const RESET_CAMPAIGN = 'RESET_CAMPAIGN';

